// ─────────────────────────────────────────────────────────────────────────────
// FAMILY VACATION DESTINATIONS
// Edit this file to add, remove, or update destinations.
// The HTML picks up changes automatically — never touch family-vacations.html
// for content updates.
//
// Workflow: draft in .md file → user approves → add entry here → HTML updates
//
// Order: Europe first (by SEA flight time), then Asia (by SEA flight time).
// directFlight: true = at least one of LAX/SEA has a nonstop.
// ─────────────────────────────────────────────────────────────────────────────

const DESTINATIONS = [

  // ── EUROPE ────────────────────────────────────────────────────────────────

  {
    id: 'reykjavik',
    name: 'Reykjavik, Iceland',
    regionKey: 'europe',
    regionLabel: 'Europe · Iceland',
    directFlight: true,
    pitch: 'The only country on earth where you can drive a loop through volcanoes, waterfalls, geysers, and black-sand beaches in a single week — and the SEA flight is shorter than the one to New York.',
    about: 'Iceland is unlike anywhere else in the world. It\'s a volcanic island at the edge of the Arctic with landscapes that look rendered, not real — black lava fields, turquoise glacier lagoons, waterfalls so large you can walk behind them, and geysers that shoot 100 feet in the air every 5-10 minutes on a predictable clock. The light in May and summer is extraordinary: the sun barely sets, and the sky at 10:30pm looks like a watercolor painting.\n\nThis is the only destination on the family list structured as a road trip rather than a basecamp. The practical model is 2-3 rental SUVs driving in convoy down the ring road. Kids get a window seat to an alien planet. Every stop is inherently photogenic. It\'s one of the most effortless shared experiences you can engineer.',
    gradient: 'linear-gradient(160deg, #0D3349 0%, #1A5E7A 40%, #4A9DB5 100%)',
    lax: { direct: false, time: '~12h 30m', airlines: 'Alaska + Icelandair (LAX → SEA → KEF)', notes: 'No nonstop from LAX. Best routing: LAX → SEA on Alaska (~2h 20m) then SEA → KEF on Icelandair (~7h 35m). Same-day connection, ~2h layover in Seattle.' },
    sea: { direct: true, time: '~7h 35m', airlines: 'Icelandair (SEA → KEF)', notes: 'Daily nonstop to Keflavik International (KEF). One of the shortest transatlantic options on this list.' },
    timeDiff: '+8h from LA (UTC in summer)',
    visa: 'Visa-free for US citizens. Schengen — 90-day entry, no paperwork needed.',
    bestTime: 'May – Aug',
    groupNotes: 'Road trip exception — multi-hotel format. Vehicle recommendation: 2-3 Toyota Land Cruisers or similar 7-seat 4WD SUVs. Rental companies inside KEF terminal: Avis, Europcar, Budget, Hertz. Book months ahead — large vehicle availability in summer is limited. Hotel sequence: Reykjavik (nights 1-2) → Selfoss → Vík → Höfn → Egilsstaðir → Mývatn → Reykjavik. Book ring road hotels many months in advance — Vík especially has very limited inventory.',
    weather: [
      { season: 'Spring', months: 'Apr – May', temp: 'High 46–53°F / 8–12°C · Low 36–43°F / 2–6°C', desc: 'Moderate rain (May is actually driest month). Sun sets ~10:30pm. All main roads open. Fewer crowds, lower prices.', rating: 4 },
      { season: 'Summer', months: 'Jun – Aug', temp: 'High 55–65°F / 13–18°C', desc: 'Nearly 24h daylight. All roads open. July–August peak crowds and prices. June is the sweet spot — full daylight, lower crowds.', rating: 5 },
      { season: 'Fall', months: 'Sep – Oct', temp: 'High 45–55°F / 7–13°C', desc: 'Northern Lights possible from late August. F-roads close in October. Cold and increasingly wet. Early September still lovely.', rating: 3 },
      { season: 'Winter', months: 'Nov – Mar', temp: 'High 25–38°F / -4–3°C', desc: 'Northern Lights season but icy roads, F-roads closed, very dark. Not recommended for this group.', rating: 2 },
    ],
    kids: [
      'Strokkur geyser — erupts every 5-10 minutes on a predictable clock. Kids try to guess the exact moment. They\'ll be wrong in a way that\'s delightful.',
      'Seljalandsfoss — a waterfall you walk behind. There\'s a path cut into the cliff. Get wet. Bring a change of clothes.',
      'Reynisfjara black sand beach — jet-black sand, towering basalt columns, ocean waves with real drama. The color contrast is otherworldly.',
      'Jökulsárlón glacier lagoon — icebergs calving into a tidal lagoon. Touch them from shore. Seals sit on them. The ice is blue.',
      'Diamond Beach — ice chunks from the lagoon on jet-black sand. Kids can pick up pieces and hold them up to the light.',
    ],
    family: [
      'Road trip format is self-pacing — if someone needs a stop, you stop. If kids are restless, you drive. The route is sequential so you always know what\'s coming next.',
      '2-3 SUVs in convoy: one leads with navigation, others follow. No coordination complexity for the group.',
      'Every major stop is walk-up accessible — no booking, no timed entry. You arrive, you see it, you move on.',
      'Long summer daylight (sun sets ~10:30pm in May) means no schedule pressure. Running late on one stop doesn\'t cost you the light.',
      'No language barrier whatsoever. Every sign is in English. Zero overhead for any member of the group.',
    ],
    adults: [
      'Blue Lagoon — geothermal spa 15 minutes from KEF airport. Book premium package. Do on arrival or departure day.',
      'Mývatn Nature Baths — less crowded than Blue Lagoon, dramatic volcanic setting. Hot pools over a geothermal lake.',
      'Forest Lagoon in Akureyri — newer infinity-pool spa with mountain views worth a stop on the return.',
      'Höfn lobster soup — langoustines from Hornafjörður fjord are exceptional. The best meal on the ring road.',
      'Whale watching from Húsavík — Iceland\'s whale watching capital. High sighting rate; May is prime season.',
    ],
    dayTrips: null,
    sketch: [
      { day: 'Sat - Arrive', highlight: 'Land KEF 9:25am. Pick up rental cars at terminal (Avis, Europcar, Budget, Hertz). Perlan Museum. Hallgrimskirkja + city walk. Check in Reykjavik.' },
      { day: 'Sun - Day 1', highlight: 'Reykjavik: Harpa Concert Hall + harbor walk + Laugavegur street. Rest day to settle after travel.' },
      { day: 'Mon - Day 2', highlight: 'Golden Circle: Thingvellir (walk between tectonic plates) + Strokkur geyser + Gullfoss. Stay Selfoss.' },
      { day: 'Tue - Day 3', highlight: 'South Coast: Seljalandsfoss (walk behind it) + Skogafoss + lunch at Freyacafe in Skogar + Reynisfjara black beach + Vik. Stay Vik.' },
      { day: 'Wed - Day 4', highlight: 'Glaciers: Jokulsarlon glacier lagoon (boat ride if weather allows) + Diamond Beach + Vestrahorn Mountain + Hofn (lobster soup). Stay Hofn.' },
      { day: 'Thu - Day 5', highlight: 'East Fjords: Djupivogur + Petra\'s stone collection (Stodvarfjordur) + scenic fjord drive + Egilsstadir (Vok Baths). Stay Egilsstadir.' },
      { day: 'Fri - Day 6', highlight: 'North Iceland: Dettifoss waterfall + Hverir mud pools + Lake Myvatn + Myvatn Nature Baths. Stay Myvatn.' },
      { day: 'Sat - Day 7', highlight: 'Godafoss + drive west + lunch in Borgarnes + Reykjavik. Stay Reykjavik.' },
      { day: 'Sun - Depart', highlight: 'Blue Lagoon (50 min from Reykjavik, 15 min from airport). Depart KEF afternoon.' },
    ],
  },

  {
    id: 'dublin',
    name: 'Dublin, Ireland',
    regionKey: 'europe',
    regionLabel: 'Europe · Ireland',
    directFlight: true,
    pitch: 'Ancient pubs, Georgian squares, the greenest countryside in Europe, and the shortest transatlantic flight on this list — Ireland is the easiest long-haul trip the family will ever take.',
    about: 'Dublin punches well above its size. It\'s a compact, walkable capital with a genuine literary and cultural identity — James Joyce, Oscar Wilde, Samuel Beckett, and Bram Stoker all called this city home. The streets are Georgian and handsome, the pubs are warm and multigenerational, and the people are among the most naturally welcoming in the world. English everywhere, no jet lag adjustment crisis, no visa friction. For a large family group with mixed international travel experience, Dublin removes every logistical barrier that makes people nervous about a long-haul trip.\n\nThe real asset is the day-trip infrastructure. From Dublin, you can reach the Wicklow Mountains in 30 minutes, ancient passage tombs in under an hour, and a string of beautiful coastal towns via the DART railway without a car.',
    gradient: 'linear-gradient(160deg, #1B4A2A 0%, #2E7A48 40%, #5EAA78 100%)',
    lax: { direct: true, time: '~10h', airlines: 'Aer Lingus (LAX → DUB)', notes: 'Daily nonstop from LAX to Dublin. Strong route, well-served. Both crews land at DUB with similar flight times.' },
    sea: { direct: true, time: '9h 10m', airlines: 'Aer Lingus (SEA → DUB)', notes: 'Daily nonstop to Dublin Airport (DUB). One of the most symmetric routings on this list — both crews direct on the same carrier.' },
    timeDiff: '+8h from LA (IST in summer)',
    visa: 'Visa-free for US citizens. Ireland is not in Schengen — separate entry, no complications.',
    bestTime: 'May – Sep',
    groupNotes: 'Anchor hotels: The Shelbourne (St. Stephen\'s Green, $500-800/night) or The Merrion (Merrion Street, $500-750/night). Both central, both have multi-room configurations for large groups. For day trips requiring transport, hire a private driver-guide van — avoids left-hand driving navigation for the group. DART rail covers coastal towns without any car needed.',
    weather: [
      { season: 'Spring', months: 'Mar – May', temp: '48–60°F / 9–16°C', desc: 'Mild and green. Some rain but not heavy. Light crowds, good prices. Late May is excellent — long evenings, everything open.', rating: 4 },
      { season: 'Summer', months: 'Jun – Aug', temp: '60–70°F / 16–21°C', desc: 'Best weather. Long daylight (sunset 10pm in June). Warmest and driest months. Crowds and prices peak in July–August.', rating: 5 },
      { season: 'Fall', months: 'Sep – Oct', temp: '52–62°F / 11–17°C', desc: 'Quieter than summer, weather still decent in September. Rain picks up in October. Good value.', rating: 4 },
      { season: 'Winter', months: 'Nov – Feb', temp: '40–50°F / 4–10°C', desc: 'Cold, frequently rainy and grey. Christmas markets in December are lovely. Not a family trip window.', rating: 2 },
    ],
    kids: [
      'Trinity College Long Room + Book of Kells — one of the most beautiful rooms in Europe: barrel-vaulted, floor-to-ceiling shelves, 200,000 ancient books. The Book of Kells is a 9th-century hand-illuminated gospel that looks like something from a fantasy novel.',
      'Glendalough — a 6th-century monastic city nestled between two glacial lakes in the Wicklow Mountains. Round tower, lake, and ruins together feel like a fairy tale. 45-minute drive from Dublin.',
      'Newgrange passage tomb — older than Stonehenge and the pyramids (3200 BC). A guided tour takes you inside the stone chamber. Kids understand "5,000 years old" better than most adults.',
      'DART train to Howth — 30-minute coastal train to a fishing village. Walk the cliff path, watch the seals, eat fish and chips on the harbor wall.',
      'Irish National Stud + Japanese Gardens — horses up close (foals in spring), plus one of the finest Japanese gardens in Europe. 1 hour from Dublin.',
    ],
    family: [
      'Most logistically frictionless destination on this list. English everywhere, no visa coordination, no dietary challenges, same-brand electrical outlets (with type G adapter).',
      'The Shelbourne and Merrion are both on or near St. Stephen\'s Green — the entire city is walkable from either hotel.',
      'DART coastal railway connects Howth, Dun Laoghaire, Dalkey, and Bray — all accessible without a car. Two full days of day trips with no logistics.',
      'Traditional pub sessions (live folk music) run from 6pm — early enough for kids. Finding a genuine session at O\'Donoghue\'s or Mulligan\'s is a shared experience everyone participates in.',
      'Ireland drives on the left, which is the one logistical quirk. For Wicklow and Newgrange day trips, hire a driver-guide van for the group.',
    ],
    adults: [
      'Mulligan\'s pub (1782) — one of Dublin\'s oldest pubs. The Guinness is poured correctly. Spend an afternoon.',
      'Chapters Restaurant tasting menu — exceptional value relative to quality in a city that prices things fairly.',
      'Whiskey trail: Jameson Distillery Bow St., Teeling Whiskey Distillery, Irish Whiskey Museum. Dublin is better for whiskey tourism than most people realize.',
      'National Gallery of Ireland — free entry, excellent permanent collection including Caravaggio\'s "The Taking of Christ" (rediscovered in a Dublin Jesuit house in 1990).',
      'Cliffs of Moher — 3 hours from Dublin, but the Atlantic cliff face is one of the world\'s great views. Best as an overnight to Clare.',
    ],
    dayTrips: [
      { name: 'Wicklow Mountains + Glendalough', desc: '45 min from Dublin. 6th-century monastic ruins, round tower, two glacial lakes, forest walks. Half day or full day. Easy with young kids.' },
      { name: 'Newgrange + Boyne Valley', desc: '45 min north. World\'s oldest passage tomb (3200 BC), UNESCO World Heritage. Guided tour inside the chamber. Combine with Hill of Tara for a full day.' },
      { name: 'DART coastal towns', desc: 'No car needed. Train south from Pearse Station: Dun Laoghaire (harbor, restaurants), Dalkey (village pub), Bray (Victorian seaside, cliff walk). 30-60 min from city center.' },
      { name: 'Howth', desc: '30 min north on the DART. Fishing village with cliff walk, seal colony, and seafood restaurants on the harbor. Perfect half-day.' },
    ],
    sketch: [
      { day: 'Sat - Arrive', highlight: 'Land DUB. Check in. Walk to Grafton Street and St. Stephen\'s Green. Easy pub dinner nearby.' },
      { day: 'Sun - Day 1', highlight: 'Trinity College Long Room + Book of Kells (pre-booked) + National Museum of Ireland + Merrion Square + pub session at O\'Donoghue\'s.' },
      { day: 'Mon - Day 2', highlight: 'Wicklow Mountains + Glendalough day trip: monastic ruins, round tower, lake walk. Lunch in Laragh village.' },
      { day: 'Tue - Day 3', highlight: 'Newgrange + Boyne Valley: guided tour inside the passage tomb, Hill of Tara. Lunch in Drogheda.' },
      { day: 'Wed - Day 4', highlight: 'DART day: Howth morning (cliff walk, seals, fish and chips) + Dun Laoghaire afternoon (harbor walk, Forty Foot swimming spot).' },
      { day: 'Thu - Day 5', highlight: 'Dublin city: Kilmainham Gaol + Irish Museum of Modern Art + Guinness Storehouse (Gravity Bar views) + Temple Bar for dinner.' },
      { day: 'Fri - Day 6', highlight: 'Irish National Stud + Japanese Gardens (1 hr south) + Kildare Village outlet shopping + farewell dinner.' },
      { day: 'Sat - Day 7', highlight: 'Phoenix Park (largest enclosed city park in Europe, free-roaming deer) + Dublin Castle + Chester Beatty Library. Final pub dinner at Mulligan\'s.' },
      { day: 'Sun - Depart', highlight: 'Morning checkout. DUB airport 45 min from city center. Both crews depart direct.' },
    ],
  },

  {
    id: 'copenhagen',
    name: 'Copenhagen, Denmark',
    regionKey: 'europe',
    regionLabel: 'Europe · Denmark',
    directFlight: true,
    pitch: 'The world\'s most livable city — design, food, and cycling culture at its best — with Legoland and the original Tivoli Gardens for the kids.',
    about: 'Copenhagen consistently ranks as one of the world\'s most livable cities, and spending a week there makes it easy to understand why. It\'s compact, strikingly beautiful, and extraordinarily well-organized — a harbor capital of colorful townhouses, Michelin-starred restaurants, and a design sensibility that permeates everything from the transit system to the park benches.\n\nFor a large family group, Copenhagen is unusually frictionless. The city is flat and almost entirely bikeable. Tivoli Gardens is walking distance from the city center and is one of the oldest and most charming amusement parks in the world. Legoland — the original, in Billund — is 2.5 hours by train. And Sweden is 35 minutes away across the Øresund Bridge. The kids can be in one country for breakfast and another for lunch without anyone boarding a plane.',
    gradient: 'linear-gradient(160deg, #2A3B5E 0%, #3D5A8A 40%, #7A9EC4 100%)',
    lax: { direct: false, time: '~13h (connect London, Frankfurt, or Amsterdam)', airlines: 'British Airways via LHR, Lufthansa via FRA, KLM via AMS', notes: 'No nonstop from LAX to Copenhagen. Best routing is via London (BA) or Frankfurt (Lufthansa). Plan for a full travel day — LAX crew arrives several hours after SEA crew.' },
    sea: { direct: true, time: '9h 15m', airlines: 'Scandinavian Airlines (SEA → CPH)', notes: 'Daily nonstop to Copenhagen Airport (CPH). Strong route on SAS.' },
    timeDiff: '+9h from LA (CEST in summer)',
    visa: 'Visa-free for US citizens. Schengen — 90-day entry.',
    bestTime: 'May – Aug',
    groupNotes: 'Anchor hotel: Hotel d\'Angleterre (Kongens Nytorv, $650-1,000/night) — adjacent to Nyhavn harbor, 90 rooms, multi-room configurations for large groups. Nimb Hotel (Tivoli-adjacent, 17 rooms) is too small for a large group as primary. Supplement with Marriott or Radisson Blu Royal (the Arne Jacobsen-designed landmark) for additional rooms. Bikes: book cargo bikes and regular bikes from Baisikeli or similar outfitter — cycling as a group is one of the best things about Copenhagen.',
    weather: [
      { season: 'Spring', months: 'Apr – May', temp: '48–60°F / 9–16°C', desc: 'Mild and green. Some rain. Long evenings begin in May. Light crowds, good prices. Late May is excellent.', rating: 4 },
      { season: 'Summer', months: 'Jun – Aug', temp: '63–72°F / 17–22°C', desc: 'Best weather. Sunset at 10pm in June. Tivoli and city beaches in full swing. Peak crowds and prices in July–August.', rating: 5 },
      { season: 'Fall', months: 'Sep – Oct', temp: '52–62°F / 11–16°C', desc: 'Quieter and cooler. September still pleasant. Rain increases in October. Good value.', rating: 3 },
      { season: 'Winter', months: 'Nov – Mar', temp: '33–42°F / 1–6°C', desc: 'Cold, dark, grey. Tivoli does a Christmas version. Not a family trip window.', rating: 2 },
    ],
    kids: [
      'Tivoli Gardens — the original amusement park (opened 1843), walking distance from the hotel. Rides for every age, live performances, and lights strung through the gardens at night. Walt Disney visited Tivoli before designing Disneyland.',
      'Legoland Billund — the original Legoland, 2.5 hours by train. Built around the factory town where Lego was invented. Irreplaceable at the source. Plan a full day.',
      'Kronborg Castle (Helsingør) — Shakespeare\'s Elsinore, a real castle on a cliff above the Øresund strait, 45 minutes by train. The dungeon and cannons alone are worth the trip.',
      'Roskilde Viking Ship Museum — five original 1,000-year-old Viking ships recovered from the fjord. 25 minutes by train. Helmets to try on, runes to decode.',
      'Dyrehaven deer park — hundreds of deer roaming freely through a royal forest north of the city. You can hand-feed them. Bakken amusement park (oldest in the world) is adjacent.',
    ],
    family: [
      'Flat city means the whole group can bike together — cargo bikes for kids, regular bikes for adults. Rental options everywhere.',
      'Tivoli is a 10-minute walk from the anchor hotel — no logistics required for the group\'s best evening activity.',
      'Sweden day trip on the Øresund train: 35 minutes from Copenhagen Central to Malmö, no passport control (Schengen), lunch in Sweden, dinner back in Denmark.',
      'LAX crew has a connection, so plan a low-key arrival day to account for the potential 3-4 hour offset from the SEA crew.',
      'Summer daylight is extraordinary — sunset at 10pm in June means full evenings for the group without rushing.',
    ],
    adults: [
      'Geranium — 3 Michelin stars, consistently ranked top 5 in the world. Requires advance reservation months ahead.',
      'Mikkeller Bar — Copenhagen\'s craft beer institution. Exceptional rotating taps. The best version of the bar is still in Copenhagen.',
      'Designmuseum Danmark — the definitive museum of Scandinavian design. Arne Jacobsen, Hans Wegner, the full canon.',
      'Frederiksberg Have — a royal baroque garden with a canal system and rowboats for rent. Quintessential Copenhagen hygge on a summer evening.',
      'Kadeau — one of the best restaurants to emerge from the Noma generation. New Nordic cuisine at its most refined.',
    ],
    dayTrips: [
      { name: 'Malmo, Sweden', desc: '35 min by train across the Oresund Bridge. Gamla Staden (Old Town), lunch at Lilla Torg square, back by afternoon. Easy half-day or full day. No passport control (Schengen).' },
      { name: 'Helsingor (Kronborg Castle)', desc: '45 min by train up the coast. Hamlet\'s Elsinore on the cliff, maritime museum, optional 5-min ferry to Helsingborg, Sweden. Full day.' },
      { name: 'Roskilde', desc: '25 min by train. Viking Ship Museum (five 1,000-year-old ships) + Roskilde Cathedral (burial site of Danish royalty). Easy half-day.' },
      { name: 'Legoland Billund', desc: '2.5 hrs by train + shuttle. Full day. The original Legoland, built around the factory where Lego was invented. Book tickets in advance in summer.' },
    ],
    sketch: [
      { day: 'Sat - Arrive', highlight: 'SEA crew lands direct. LAX crew arrives via connection — plan a relaxed first evening. Walk to Nyhavn for dinner along the harbor.' },
      { day: 'Sun - Day 1', highlight: 'Tivoli Gardens: full day of rides, performances, and evening lights. 10-min walk from hotel. No logistics required.' },
      { day: 'Mon - Day 2', highlight: 'Roskilde day trip (Viking Ship Museum) + back for Torvehallerne market afternoon + Norreport neighborhood.' },
      { day: 'Tue - Day 3', highlight: 'Bike day: Christiania + Christiansborg Palace + Rosenborg Castle + King\'s Garden picnic + harbor swim at Islands Brygge.' },
      { day: 'Wed - Day 4', highlight: 'Helsingor day trip: Kronborg Castle + optional ferry to Helsingborg (Sweden) and back.' },
      { day: 'Thu - Day 5', highlight: 'Malmo, Sweden day trip: Oresund train, Gamla Staden, lunch at Lilla Torg, back by late afternoon. Dinner at Kadeau.' },
      { day: 'Fri - Day 6', highlight: 'Legoland Billund: full day by train + shuttle. Back by evening.' },
      { day: 'Sat - Day 7', highlight: 'Designmuseum Danmark + Frederiksberg Have (rowboats on the canal) + farewell dinner at Geranium or Relae.' },
      { day: 'Sun - Depart', highlight: 'Morning checkout. CPH airport 15 min by train. SEA crew direct; LAX crew connects.' },
    ],
  },

  {
    id: 'amsterdam',
    name: 'Amsterdam, Netherlands',
    regionKey: 'europe',
    regionLabel: 'Europe · Netherlands',
    directFlight: true,
    pitch: 'Canal houses, world-class museums, and — if the timing is right — the most spectacular flower display on earth: 7 million tulips in bloom at Keukenhof, 30 minutes from the city.',
    about: 'Amsterdam is a city built on water, and that fact shapes everything about it. Roughly 165 canals ring the historic center, crossed by 1,500 bridges, lined with narrow 17th-century townhouses leaning gently toward the water. It is one of the most distinctively beautiful cities in the world — not dramatic like Paris or Rome, but intricately lovely, with a human scale that makes it feel immediately navigable.\n\nFor the family group, Amsterdam has a uniquely clean routing profile: both LAX and SEA have daily nonstops on KLM, so no one arrives on a different schedule. The canal belt is walkable, day trips by fast rail reach Haarlem in 15 minutes and The Hague in 50. And if the trip falls in April or May, Keukenhof — the largest flower garden in the world with 7 million bulbs — is a 30-minute bus ride away.',
    gradient: 'linear-gradient(160deg, #7A4010 0%, #B86820 40%, #E0A050 100%)',
    lax: { direct: true, time: '~10h 30m', airlines: 'KLM (LAX → AMS)', notes: 'Daily nonstop from LAX to Schiphol. KLM is an excellent carrier. Both crews land at AMS on the same airline with similar flight times.' },
    sea: { direct: true, time: '9h 45m', airlines: 'KLM (SEA → AMS)', notes: 'Daily nonstop to Amsterdam Schiphol (AMS). One of the most symmetric routings on this list — both crews direct on KLM.' },
    timeDiff: '+9h from LA (CEST in summer)',
    visa: 'Visa-free for US citizens. Schengen — 90-day entry.',
    bestTime: 'Apr – May (Keukenhof + tulips) · Jun – Aug (weather)',
    groupNotes: 'Anchor hotel: Waldorf Astoria Amsterdam (Herengracht canal, $700-1,200/night) — five adjoining 17th-century canal houses, suite configurations for large groups. Hotel V Nesplein is the mid-range alternative (~$300-500/night). For 10+, supplement with nearby boutique canal hotels if needed. Keukenhof timing: if visiting April-May, it\'s a half-day trip that becomes a defining experience. If visiting June-August, skip the garden but city and weather are ideal. OV-chipkaart transit cards cover all trains, trams, buses.',
    weather: [
      { season: 'Spring', months: 'Apr – May', temp: '50–63°F / 10–17°C', desc: 'Tulip season. Keukenhof open. Fields in bloom between Amsterdam and Lisse. Some rain but clear days. Best window if flowers are a priority.', rating: 5 },
      { season: 'Summer', months: 'Jun – Aug', temp: '65–75°F / 18–24°C', desc: 'Best weather. Long evenings. Canal life and Vondelpark at full swing. Crowds and prices peak July–August. Keukenhof closed.', rating: 4 },
      { season: 'Fall', months: 'Sep – Oct', temp: '52–62°F / 11–16°C', desc: 'Quieter, cooler, some rain. Museums without crowds. Good value.', rating: 3 },
      { season: 'Winter', months: 'Nov – Mar', temp: '36–45°F / 2–7°C', desc: 'Cold and damp. Christmas markets are pleasant. Not a family trip window.', rating: 2 },
    ],
    kids: [
      'Keukenhof Gardens (April-May only) — 7 million tulips in bloom across 79 acres, designed anew every year. The flower fields between Amsterdam and the garden are visible from the bus. Julie will remember this. Jordan will too.',
      'NEMO Science Museum — hands-on science museum built into a ship-shaped building on the harbor. Five floors of experiments, water tables, and interactive chemistry.',
      'Rijksmuseum — the Night Watch in person is larger and more powerful than any reproduction suggests. The children\'s audio guide sends kids on a treasure-hunt style tour.',
      'Vondelpark — Amsterdam\'s central park. Paddle boats on the pond, playgrounds, open-air theater in summer. Good for burning energy mid-trip.',
      'Dutch cheese and stroopwafel — at the Albert Cuyp market, buying Gouda and eating stroopwafels hot off the iron is the sensory memory of Amsterdam for kids.',
    ],
    family: [
      'Both LAX and SEA have daily KLM nonstops — one of the most symmetric routings on this list. Both crews arrive at Schiphol at similar times with no connection complexity.',
      'Schiphol to Amsterdam Centraal by train runs every 10 minutes (15 min, €5/person). Arrival for a large group is genuinely smooth.',
      'Amsterdam Centraal to anywhere in the Netherlands is fast rail — Utrecht 25 min, Haarlem 15 min, The Hague 50 min. No car rental needed for any day trip.',
      'Private electric canal boat rental (no license needed) for 2-3 hours — the whole group on one boat, navigating the canals. Genuinely fun and different from anything else on this list.',
      'Keukenhof timing: if the group goes April-May, half a day at the gardens becomes the defining experience. If June-August, the city and weather are ideal instead.',
    ],
    adults: [
      'Rijksmuseum — the greatest collection of Dutch Golden Age painting in the world. Rembrandt\'s Night Watch, Vermeer\'s Milkmaid. Budget 3 hours.',
      'Anne Frank House — requires advance booking (sells out weeks ahead in summer). One of the most important historical sites in Europe.',
      'Genever tasting at Wynand Fockink (1679) — the oldest jenever tasting house in Amsterdam. House blend, stand at the bar, pour from the full glass without lifting it. Local tradition.',
      'Indonesian rijsttafel at Blauw or Sama Sebo — the definitive Amsterdam dining experience. A dozen small dishes in sequence: satay, rendang, gado gado, tempeh, rice.',
      'Stedelijk Museum — one of Europe\'s best contemporary art collections. Strong on De Stijl, Mondrian, and rotating exhibitions.',
    ],
    dayTrips: [
      { name: 'Haarlem', desc: '15 min by train. Beautiful Dutch city with a better-preserved historic center than Amsterdam, Frans Hals Museum, and a Saturday flower market. Half day.' },
      { name: 'Delft', desc: '55 min by train. Home of Delft blue pottery and Vermeer. Markt square and Nieuwe Kerk are beautiful. Buy hand-painted Delft tiles. Half day.' },
      { name: 'The Hague', desc: '50 min by train. Dutch parliament, Mauritshuis museum (Vermeer\'s Girl with a Pearl Earring, in person), and Scheveningen beach (North Sea). Full day.' },
      { name: 'Utrecht', desc: '25 min by train. Canal city with younger energy, Dom Tower climb, wharf-level canal restaurants, excellent coffee scene. Half day or full day.' },
      { name: 'Keukenhof (April-May only)', desc: '30 min by bus from Schiphol. 79 acres, 7 million bulbs, designed anew each year. Open late March to mid-May only. Book bus tickets in advance.' },
    ],
    sketch: [
      { day: 'Sat - Arrive', highlight: 'Both crews land at Schiphol. Train to Centraal (15 min). Check in. Walk the Jordaan neighborhood. Canal-side dinner at Brouwerij \'t IJ.' },
      { day: 'Sun - Day 1', highlight: 'Rijksmuseum (Night Watch, Vermeer) + Van Gogh Museum + Vondelpark picnic + canal boat rental for the group in the evening.' },
      { day: 'Mon - Day 2', highlight: 'Anne Frank House (pre-booked) + Jordaan neighborhood walk + Albert Cuyp market lunch + NEMO Science Museum for kids.' },
      { day: 'Tue - Day 3', highlight: 'Keukenhof (Apr-May) or Haarlem (Jun-Aug) day trip. Flower fields visible from the bus en route. Back by mid-afternoon.' },
      { day: 'Wed - Day 4', highlight: 'Delft + The Hague day trip: Mauritshuis (Girl with a Pearl Earring) + Delft Markt and blue pottery + optional Scheveningen beach.' },
      { day: 'Thu - Day 5', highlight: 'Utrecht day trip: Dom Tower, canal restaurants, city wander. Or Amsterdam city day: Stedelijk + Waterlooplein flea market + Wynand Fockink jenever tasting.' },
      { day: 'Fri - Day 6', highlight: 'Amsterdam at leisure: neighborhood exploration, final market shopping, Indonesian rijsttafel dinner at Blauw.' },
      { day: 'Sat - Day 7', highlight: 'Morning canal walk + Hortus Botanicus + farewell lunch at Rijks (inside the Rijksmuseum).' },
      { day: 'Sun - Depart', highlight: 'Morning checkout. Train to Schiphol (15 min). Both crews depart direct on KLM.' },
    ],
  },

  {
    id: 'paris',
    name: 'Paris, France',
    regionKey: 'europe',
    regionLabel: 'Europe · France',
    directFlight: true,
    pitch: 'The most visited city in the world — and it earns it. Art, food, and architecture at a density that makes every other city feel like it\'s still trying.',
    about: 'Paris is the benchmark against which every other city gets measured. It has been the center of Western art, cuisine, fashion, and intellectual life for three centuries, and the infrastructure built around that centrality is extraordinary. The Louvre, the Musée d\'Orsay, the Eiffel Tower, Versailles, and Giverny are all within a day-trip radius of a single Left Bank hotel.\n\nFor a family group with strollers and young kids, the key variable is neighborhood. The goal is to maximize stroller walking and minimize metro dependency. St-Germain (6th) is the default — classic Parisian charm, walkable to the Left Bank, Luxembourg Gardens nearby. The 7th (Eiffel/Rue Cler area) offers slightly better stroller access: calmer streets, flat terrain, direct walk to Champ de Mars. Ranking for stroller-friendliness: 7th > St-Germain > Le Marais > 1st.',
    gradient: 'linear-gradient(160deg, #4A2840 0%, #8A4A70 40%, #C88AAA 100%)',
    lax: { direct: true, time: '10h 45m', airlines: 'Air France (LAX → CDG)', notes: 'Daily nonstop from LAX to Charles de Gaulle. Departs ~1:40pm, arrives 9:25am+1. Both crews land at CDG within ~90 minutes of each other.' },
    sea: { direct: true, time: '9h 35m', airlines: 'Air France (SEA → CDG)', notes: 'Daily nonstop to Charles de Gaulle. Departs ~1:30pm, arrives 8:05am+1.' },
    timeDiff: '+9h from LA (CEST in summer)',
    visa: 'Visa-free for US citizens. Schengen — 90-day entry.',
    bestTime: 'Apr – Jun · Sep',
    groupNotes: 'Anchor hotel: Citadines Saint-Germain-des-Prés (6th arrondissement, aparthotel format, $400-650/night for family unit with kitchen). Kitchen access matters for a large group: easy breakfasts in, one stay-in dinner from La Grande Épicerie per week cuts cost significantly. Alternatively, private apartment rental through Paris Attitude or Lodgis in St-Germain or the 7th gives the group a shared living space. RER B from CDG to Saint-Michel takes ~40 minutes. RER C to Versailles from Saint-Michel is 36 minutes.',
    weather: [
      { season: 'Spring', months: 'Apr – Jun', temp: 'High 66–69°F / 19–21°C · Low 49–52°F / 9–11°C', desc: 'Best window. Parks in bloom, café terraces open, sun sets 9:30pm in May. Giverny garden at peak. Crowds manageable.', rating: 5 },
      { season: 'Summer', months: 'Jul – Aug', temp: 'High 75–85°F / 24–30°C', desc: 'Hot and very crowded. Major sites have long queues. Parisians leave in August. Still beautiful but not the best version.', rating: 3 },
      { season: 'Fall', months: 'Sep – Oct', temp: 'High 58–68°F / 14–20°C', desc: 'September is excellent — summer crowds gone, weather still warm, restaurant reservations easier. October cools and greys.', rating: 4 },
      { season: 'Winter', months: 'Nov – Mar', temp: 'High 38–48°F / 3–9°C', desc: 'Cold and grey. Christmas lights on Champs-Élysées are beautiful. Museums uncrowded. Not a family trip window.', rating: 2 },
    ],
    kids: [
      'Jardin du Luxembourg — toy sailboats on the pond, carousel, and playground. The toy boat rental is a sensory memory of Paris that children carry for years.',
      'Eiffel Tower + Champ de Mars — pre-book summit tickets. The park below has a playground and is perfect for a picnic.',
      'Palais Royal — the Colonnes de Buren (black-and-white striped columns in the courtyard) are an open sculpture playground. Kids immediately start jumping between them.',
      'Musée de l\'Orangerie — Monet\'s Water Lilies in two immersive oval rooms. Bring coloring supplies for kids; the scale and quiet are genuinely peaceful.',
      'Sainte-Chapelle — Gothic chapel with floor-to-ceiling stained glass. Even young kids respond to the light.',
    ],
    family: [
      'Both LAX and SEA have daily Air France nonstops. Both crews land at CDG within ~90 minutes of each other — one of the cleanest arrival logistics on this list.',
      'Stroller-first base camp in St-Germain or the 7th puts Luxembourg Gardens, the Seine walk, and Musée d\'Orsay all within stroller distance. Metro dependency is minimal.',
      'The itinerary is naturally structured by arrondissement — each day covers one neighborhood cluster, minimizing transit and maximizing walking. Kids do better with neighborhood days than landmark-hopping.',
      'May is ideal: 66-69°F highs, sun sets at 9:30pm, crowds manageable, everything open including Giverny.',
      'Versailles (RER C, 36 min) and Giverny (90 min by car, open April-November) both work as full-day excursions without changing hotels.',
    ],
    adults: [
      'Musée d\'Orsay — the Impressionist collection (Monet, Renoir, Van Gogh, Cézanne) in a converted railway station. Visit an hour before closing when crowds thin.',
      'Galeries Lafayette rooftop (Creatures café) — lunch with a panoramic Paris view. Unpretentious and excellent.',
      'Palais Garnier — the Paris opera house. Tour the interior even without attending a performance; the chandelier and the Chagall-painted ceiling are extraordinary.',
      'Seine river cruise at night — Bateaux Mouches or a private boat. The illuminated bridges are Paris at its most cinematic.',
      'La Grande Épicerie de Paris — Paris\'s best food hall, at Le Bon Marché in St-Germain. Assemble a stay-in dinner: cheese board, ready-to-heat main, exceptional desserts.',
    ],
    dayTrips: [
      { name: 'Versailles', desc: '36 min by RER C from Saint-Michel Notre-Dame. Hall of Mirrors, formal gardens, golf cart or bike rental to cover the grounds. Book tickets well in advance. Full day.' },
      { name: 'Giverny', desc: '90 min by car or organized coach. Monet\'s house and the water lily garden that inspired the paintings. Open April-November. Half day; can combine with a Normandy coast stop.' },
    ],
    sketch: [
      { day: 'Sat - Arrive', highlight: 'Land CDG (LAX ~9:25am / SEA ~8:05am). Check in. Stroll St-Germain: Pont Neuf + Luxembourg Gardens (playground, toy sailboats). Dinner at La Citrouille.' },
      { day: 'Sun - Day 1', highlight: 'Rue Cler morning (Le Petit Cler breakfast, picnic supplies) + Eiffel Tower + Champ de Mars picnic + Seine river walk + Musee d\'Orsay (last hour before closing).' },
      { day: 'Mon - Day 2', highlight: 'Palais Royal (Colonnes de Buren) + Galerie Vivienne + Tuileries Garden + Musee de l\'Orangerie (Water Lilies). Stay-in dinner from La Grande Epicerie.' },
      { day: 'Tue - Day 3', highlight: 'Ile de la Cite: Notre-Dame + Sainte-Chapelle + Le Marais: L\'As du Fallafel lunch + Place des Vosges + Rue des Francs-Bourgeois boutiques.' },
      { day: 'Wed - Day 4', highlight: 'Montmartre: Sacre-Coeur views + Place du Tertre + La Maison Rose. Evening: Seine river cruise.' },
      { day: 'Thu - Day 5', highlight: '8th and 9th: Arc de Triomphe + Champs-Elysees + Palais Garnier + Galeries Lafayette (Creatures rooftop lunch).' },
      { day: 'Fri - Day 6', highlight: 'Versailles day trip: RER C from Saint-Michel (36 min). Palace, Hall of Mirrors, formal gardens.' },
      { day: 'Sat - Day 7', highlight: 'Giverny day trip: Monet\'s house and water lily garden. Back by late afternoon. Final dinner in St-Germain.' },
      { day: 'Sun - Depart', highlight: 'Morning checkout. RER B from Saint-Michel to CDG (~45 min). LAX crew departs 1:30pm, SEA crew departs 10:25am.' },
    ],
  },

  {
    id: 'barcelona',
    name: 'Barcelona, Spain',
    regionKey: 'europe',
    regionLabel: 'Europe · Spain',
    directFlight: true,
    pitch: 'Architecture unlike anywhere else on earth, a Mediterranean beach five minutes from the city center, and the most vibrant food scene in Spain.',
    about: 'Barcelona is the kind of city that ruins other cities for you. Gaudí\'s buildings look like they came from another planet — the Sagrada Família has been under construction since 1882 and still isn\'t finished, and it remains the most extraordinary building most visitors have ever seen. The city has a beach, a Gothic quarter with 2,000-year-old Roman foundations, Michelin-starred restaurants, and a cultural energy that runs from the Picasso Museum to a football match at Camp Nou.\n\nFor a large family group, Barcelona works because the city is naturally organized around neighborhoods. Each barrio has its own character and can fill a day without anyone getting in a car. The beach is a 10-minute walk from the Gothic Quarter. Day trips by train reach Montserrat (a mountain monastery), Girona (a medieval walled city), and the Costa Brava.',
    gradient: 'linear-gradient(160deg, #8E1A10 0%, #C03820 40%, #E87840 100%)',
    lax: { direct: false, time: '~13h (via Madrid)', airlines: 'Iberia via MAD, American via MAD', notes: 'No nonstop from LAX to Barcelona. Iberia and American fly LAX-MAD nonstop (~11h), then MAD-BCN is a 1.5h domestic hop. LAX crew arrives several hours after SEA crew.' },
    sea: { direct: true, time: '10h 40m', airlines: 'Level (SEA → BCN)', notes: 'Seasonal nonstop to Barcelona El Prat (BCN). Verify current schedule — Level operates this route but frequency varies by season.' },
    timeDiff: '+9h from LA (CEST in summer)',
    visa: 'Visa-free for US citizens. Schengen — 90-day entry.',
    bestTime: 'May – Jun · Sep',
    groupNotes: 'Anchor hotel: Hotel Arts Barcelona (Port Olímpic, beachfront, $550-900/night) — direct beach access, 483 rooms, good large-group configurations. Mandarin Oriental Barcelona (Passeig de Gràcia) is the alternative if the group prefers the modernista district over the beach. No car needed within the city — metro, taxis, and Cabify cover everything. Rent cars only for Costa Brava or Girona day trips. Shoulder season (May-June, September) strongly recommended — July-August beach and Sagrada Família crowds are a real problem for a large group.',
    weather: [
      { season: 'Spring', months: 'May – Jun', temp: '65–78°F / 18–26°C', desc: 'Best window. Perfect temperatures, sea warming up, city before peak crowds. Long evenings by June.', rating: 5 },
      { season: 'Summer', months: 'Jul – Aug', temp: '85–90°F / 29–32°C', desc: 'Hot and very crowded. Beach packed wall-to-wall. Sagrada Família queues enormous. Still beautiful but not the best version.', rating: 3 },
      { season: 'Fall', months: 'Sep – Oct', temp: '70–78°F / 21–26°C', desc: 'September is excellent — sea still warm (23°C), crowds drop sharply, prices soften. Second-best window.', rating: 5 },
      { season: 'Winter', months: 'Nov – Mar', temp: '50–58°F / 10–14°C', desc: 'Mild by European standards. No beach weather. Museums and architecture without crowds.', rating: 3 },
    ],
    kids: [
      'Park Güell — Gaudí\'s mosaic-covered hillside park. The dragon stairway, the terrace with broken-tile benches, the stone viaducts that look melted. Book timed entry for the monumental zone in advance.',
      'Barceloneta Beach — a proper Mediterranean beach 10 minutes from the Gothic Quarter. Sandy, calm, and walkable from the hotel.',
      'Montjuïc cable car — gondola over the port and city to the castle on the hill. Views across the sea and the rooftops.',
      'Tibidabo amusement park — classic old amusement park on the hilltop with a Ferris wheel and a tiny plane ride operating since 1921.',
      'Camp Nou stadium tour — even non-football families are impressed by the scale. If there\'s a match during the trip, go.',
    ],
    family: [
      'Beach + city in one destination — nobody has to compromise. Beach day and museum day in the same trip, walking distance from each other.',
      'Spanish meal culture is deeply family-friendly once the timing adjustment is made. Late dinner at 9pm sounds wrong until you\'re doing it.',
      'SEA crew has a direct flight; LAX crew connects via Madrid. Plan a relaxed arrival day to account for the offset.',
      'Barcelona\'s neighborhoods are naturally day-sized — Gothic Quarter, El Born, Eixample, Gràcia each fill a day without transport pressure.',
      'Shoulder season strongly recommended — July-August crowds at Sagrada Família and Barceloneta are a real problem with young kids.',
    ],
    adults: [
      'Sagrada Família — spend two hours inside and outside. There is no building like it anywhere. Book timed entry well in advance.',
      'Disfrutar — one of the world\'s best restaurants (World\'s 50 Best top 5). Avant-garde tasting menu. Book months ahead.',
      'El Xampanyet — the best cava bar in El Born. House cava, anchovies, standing room only. Go at 7pm before dinner.',
      'Palau de la Música Catalana — a Moderniste concert hall with a stained-glass ceiling that is one of the most beautiful interiors in Europe. Attend any performance.',
      'Wine: Priorat (intense, mineral Garnacha) and Penedès (the Cava source region, 45 min by train). Both doable as day-trip extensions.',
    ],
    dayTrips: [
      { name: 'Montserrat', desc: '45 min by train from Placa Espanya + rack railway (cremallera) up the mountain. Benedictine monastery, dramatic rock formations, hiking trails. The rack railway is a thrill for kids. Half or full day.' },
      { name: 'Girona', desc: '38 min by AVE high-speed train. Beautifully preserved medieval walled city with a Jewish quarter, cathedral, and colorful houses along the Onyar river. Full day.' },
      { name: 'Costa Brava', desc: '1.5-2 hrs by car. Dramatic limestone coves, clear water, fishing villages (Calella de Palafrugell, Cadaques). Best as an overnight. Half-day swim stop doable with a car.' },
      { name: 'Sitges', desc: '35 min by train. Charming beach town with a beautiful old quarter, excellent seafood, and calmer beaches than Barceloneta. Easy half-day.' },
    ],
    sketch: [
      { day: 'Sat - Arrive', highlight: 'SEA crew lands direct. LAX crew arrives via Madrid — plan a relaxed evening. Walk to Barceloneta beach for sunset. Dinner at a beachside chiringuito.' },
      { day: 'Sun - Day 1', highlight: 'Gothic Quarter: Roman walls + Barcelona Cathedral + Placa Reial + El Born: Mercat de Santa Caterina, pintxos lunch at El Xampanyet. Afternoon: Barceloneta beach.' },
      { day: 'Mon - Day 2', highlight: 'Sagrada Familia (pre-booked, 2 hours) + lunch in Gracia neighborhood + Park Guell (pre-booked monumental zone). Evening at Passeig de Gracia.' },
      { day: 'Tue - Day 3', highlight: 'Montserrat day trip: train from Placa Espanya + cremallera rack railway. Monastery, rock formations, hiking. Back by late afternoon.' },
      { day: 'Wed - Day 4', highlight: 'Eixample modernisme walk: Casa Batllo + Casa Mila (La Pedrera) + lunch on Rambla de Catalunya. Afternoon: Tibidabo or Montjuic cable car.' },
      { day: 'Thu - Day 5', highlight: 'Girona day trip: AVE train (38 min). Medieval walls, Jewish quarter, cathedral, Onyar river houses. Lunch in Girona.' },
      { day: 'Fri - Day 6', highlight: 'Beach day at Barceloneta or day trip to Sitges (35 min by train). Evening: Palau de la Musica Catalana performance.' },
      { day: 'Sat - Day 7', highlight: 'Picasso Museum + El Born neighborhood wander + farewell paella lunch at 7 Portes (operating since 1836).' },
      { day: 'Sun - Depart', highlight: 'Morning checkout. El Prat airport 35 min by Aerobus from Placa Catalunya. SEA crew direct; LAX crew connects via Madrid.' },
    ],
  },

  {
    id: 'rome',
    name: 'Rome, Italy',
    regionKey: 'europe',
    regionLabel: 'Europe · Italy',
    directFlight: true,
    pitch: 'The entire ancient world in one city — the Colosseum, the Vatican, the Pantheon — and every dinner is an event.',
    about: 'Rome is not a city you run out of. It has been continuously inhabited for nearly 3,000 years and the accumulation of that history is everywhere: temples embedded in medieval churches, classical fountains at the center of Baroque piazzas, ancient roads still in use. The Colosseum is 2,000 years old and still the largest amphitheater ever built. The Pantheon\'s dome was the largest in the world for 1,300 years. Walking Rome is walking through layers of time in a way that no other city on earth replicates.\n\nFor a large family group, Rome works because it is inherently spectacular at every level. Kids don\'t need context to understand the Colosseum — the scale does the work. Adults don\'t need a guide to appreciate a plate of cacio e pepe in a trattoria that\'s been open since 1890. The city is compact enough that the main sites are walkable from a single central hotel, and day trips to Pompeii and Florence run by fast train.',
    gradient: 'linear-gradient(160deg, #6B3010 0%, #AA5825 40%, #D49060 100%)',
    lax: { direct: true, time: '~11h 30m', airlines: 'Delta, United, ITA Airways (LAX → FCO)', notes: 'Multiple daily nonstops from LAX to Rome Fiumicino. Delta and United are the strongest options. Both crews land at FCO with similar flight times.' },
    sea: { direct: true, time: '~11h', airlines: 'Norse Atlantic / Condor (SEA → FCO)', notes: 'Seasonal nonstop to Rome Fiumicino. Verify current schedule — route operated by budget long-haul carriers; availability varies by season.' },
    timeDiff: '+9h from LA (CEST in summer)',
    visa: 'Visa-free for US citizens. Schengen — 90-day entry.',
    bestTime: 'Mar – May · Sep – Oct',
    groupNotes: 'Anchor hotel: Hotel de Russie (Via del Babuino, $700-1,200/night) — 122 rooms, terraced garden, central location between Piazza del Popolo and the Spanish Steps. Palazzo Manfredi (adjacent to the Colosseum, rooftop with direct Colosseum views) is the more dramatic option. For Trastevere-based alternatives: quieter, more local, excellent for families with young kids. Leonardo Express train from FCO airport to Roma Termini runs every 30 minutes (32 min, €14/person). Book Vatican and Colosseum timed entry as early as possible — they sell out weeks ahead.',
    weather: [
      { season: 'Spring', months: 'Mar – May', temp: '55–72°F / 13–22°C', desc: 'Best window. Mild, green, wildflowers. Long evenings by May. Manageable crowds. Everything open.', rating: 5 },
      { season: 'Summer', months: 'Jun – Aug', temp: '85–95°F / 30–35°C', desc: 'Very hot. Major sites extremely crowded and require early starts. July-August difficult with young kids. Avoid.', rating: 2 },
      { season: 'Fall', months: 'Sep – Oct', temp: '65–78°F / 18–26°C', desc: 'Excellent. Summer crowds gone, warm days, cooler evenings. September is the sweet spot.', rating: 5 },
      { season: 'Winter', months: 'Nov – Feb', temp: '45–55°F / 7–13°C', desc: 'Cool and quiet. Christmas in Rome is charming. Museums uncrowded. Manageable but not ideal for kids.', rating: 3 },
    ],
    kids: [
      'Colosseum — the scale is incomprehensible until you\'re inside it. Book gladiator experience tickets in advance; kids put on a costume and "fight" in the arena. Theatrical and memorable.',
      'Vatican Museums + Sistine Chapel — even a 5-year-old understands Michelangelo painted the ceiling lying on his back for four years. Book timed entry well in advance.',
      'Trevi Fountain — throw a coin over your left shoulder with your right hand. Legend says you\'ll return to Rome. Jordan will want to throw many coins.',
      'Borghese Gallery — Bernini\'s sculptures (Daphne transforming into a tree, Pluto grabbing Persephone) look physically impossible. Requires advance booking; max 2 hours per visit.',
      'Explora — Rome\'s children\'s museum, designed for ages 3-12. Good for an afternoon when the kids need a break from ancient ruins.',
    ],
    family: [
      'Rome\'s centro storico is compact and largely walkable — the Colosseum, Roman Forum, Trevi Fountain, Pantheon, Piazza Navona, and the Vatican are all within 30-40 minutes on foot of each other.',
      'No car needed for the entire week. Taxis and walking cover the city; fast trains cover day trips.',
      'Italian culture is multigenerationally warm. Children are adored everywhere; grandparents treated with great respect. This destination works for every age in the group.',
      'Evening passeggiata (the ritual evening walk) is a natural group activity — dress up slightly, join the crowds near the Pantheon, eat gelato.',
      'Book Vatican and Colosseum timed entry as early as possible — these sell out weeks ahead in shoulder season and months ahead in summer.',
    ],
    adults: [
      'Roscioli deli and restaurant — arguably the best cacio e pepe in Rome. Also an exceptional wine shop. Book the restaurant table weeks ahead.',
      'Borghese Gallery — book well in advance (360 visitors per 2-hour slot). Bernini\'s marble sculptures are among the most extraordinary objects ever made.',
      'Wine: Frascati (the local Castelli Romani white, drunk cold in summer), Cesanese (the local red), and anything from the sommelier at Roscioli.',
      'Campo de\'Fiori evening — the square shifts from morning produce market to aperitivo scene by evening. Negroni at a terrace bar as the light goes gold.',
      'Pompeii day trip — one of the most important archaeological sites in the world. 2.5 hours by train from Roma Termini. A full day minimum.',
    ],
    dayTrips: [
      { name: 'Pompeii + Herculaneum', desc: '2.5 hrs by train (Frecciarossa to Naples, then Circumvesuviana local). Pompeii is vast; Herculaneum is smaller and better preserved. Do one or both. Full day.' },
      { name: 'Amalfi Coast', desc: '3 hrs to Salerno or Naples, then ferry or bus along the coast. Best as an overnight to Positano or Ravello. One of the world\'s great natural spectacles.' },
      { name: 'Florence', desc: '1.5 hrs by Frecciarossa high-speed train. Uffizi Gallery, the Duomo, Ponte Vecchio, the David at Accademia. Full day or overnight.' },
      { name: 'Castelli Romani', desc: '45 min by train from Termini. Hill towns (Frascati, Castel Gandolfo), lake swimming at Lago Albano, wine tasting. Easy half-day.' },
      { name: 'Orvieto', desc: '1 hr by train. Medieval city on a volcanic cliff with a cathedral whose facade is one of the finest examples of Italian Gothic architecture. Half day.' },
    ],
    sketch: [
      { day: 'Sat - Arrive', highlight: 'Land FCO. Leonardo Express to Roma Termini (32 min). Check in. Evening passeggiata around the Pantheon and Piazza Navona. Dinner at a nearby trattoria.' },
      { day: 'Sun - Day 1', highlight: 'Colosseum + Roman Forum + Palatine Hill (pre-booked combined ticket, half day) + afternoon rest + Trastevere dinner at Da Enzo al 29.' },
      { day: 'Mon - Day 2', highlight: 'Vatican Museums + Sistine Chapel + St. Peter\'s Basilica (pre-booked, full morning) + lunch near Castel Sant\'Angelo + Borghese Gallery (pre-booked).' },
      { day: 'Tue - Day 3', highlight: 'Pompeii day trip: Frecciarossa to Naples (1.5 hrs) + Circumvesuviana to Pompeii (40 min). Full day at the ruins.' },
      { day: 'Wed - Day 4', highlight: 'Centro storico on foot: Trevi Fountain + Spanish Steps + Pantheon + Campo de\' Fiori market (morning) + Flavio al Velavevodetto for lunch. Aperitivo at dusk.' },
      { day: 'Thu - Day 5', highlight: 'Florence day trip: Frecciarossa (1.5 hrs). Uffizi Gallery (pre-book), Ponte Vecchio, the David at Accademia. Back by evening.' },
      { day: 'Fri - Day 6', highlight: 'Trastevere neighborhood morning + Villa Borghese park + Pincian Hill terrace (best free view of Rome) + Roscioli for dinner (pre-booked).' },
      { day: 'Sat - Day 7', highlight: 'Castelli Romani half-day (Frascati wine, Lago Albano) + back to Rome by afternoon. Final gelato at Giolitti. Last dinner in the centro storico.' },
      { day: 'Sun - Depart', highlight: 'Morning checkout. Leonardo Express to FCO (32 min). LAX crew direct; SEA crew on seasonal direct or via connection.' },
    ],
  },

  // ── ASIA ──────────────────────────────────────────────────────────────────

  {
    id: 'shanghai',
    name: 'Shanghai, China',
    regionKey: 'asia',
    regionLabel: 'Asia · China',
    directFlight: true,
    pitch: 'The most international city in Asia — art deco Bund architecture, the world\'s fastest train, and a food scene that spans 1,000 years of Chinese culinary tradition.',
    about: 'Shanghai is China\'s most cosmopolitan city and its most immediately navigable for first-time visitors. The Bund — a mile-long waterfront promenade of 1920s and 30s colonial-era buildings facing the Pudong skyline — is one of the great urban vistas in the world: art deco on one side, science fiction on the other. The city is enormous but organized around neighborhoods that are human in scale: the French Concession is leafy and beautiful; the Old City and Yu Garden recall imperial China; Tianzifang is a warren of converted alleyways with galleries and cafés.\n\nFor a large family group, Shanghai offers the clearest on-ramp to China. The infrastructure is exceptional — the metro is clean and extensive; the airport maglev train reaches 430km/h and connects to the city in 8 minutes. Day trips by high-speed rail reach Suzhou (30 min) and Hangzhou (45 min), both UNESCO-level destinations in their own right.',
    gradient: 'linear-gradient(160deg, #0A1E3A 0%, #183A68 40%, #4070A8 100%)',
    lax: { direct: true, time: '~13h', airlines: 'United, Air China (LAX → PVG)', notes: 'Daily nonstop from LAX to Shanghai Pudong (PVG). United and Air China both serve the route. Both crews land at PVG with similar flight times.' },
    sea: { direct: true, time: '13h 05m', airlines: 'Hainan Airlines / United (SEA → PVG)', notes: 'Nonstop to Shanghai Pudong (PVG). Verify current carrier and frequency — multiple airlines have operated this route; confirm schedule before booking.' },
    timeDiff: '+15h from LA (summer) · +16h (winter)',
    visa: 'Tourist L visa required for most nationalities — apply 4-6 weeks in advance. Maggie/Bill/Jordan already hold 10-year China visas. 144-hour visa-free transit may apply for US citizens arriving at PVG — consult current rules before booking.',
    bestTime: 'Sep – Nov · Mar – May',
    groupNotes: 'Anchor hotel: The Peninsula Shanghai (The Bund, $500-900/night) — 235 rooms, directly on the Bund. Waldorf Astoria Shanghai on the Bund (converted 1910 Shanghai Club building) is the atmospheric alternative. Mid-range alternative: The Middle House (French Concession, $300-500/night). DiDi is the primary transport — set it up for the group on arrival. Maglev train from PVG airport to Longyang Road metro station (8 min, 430km/h) is the most thrilling airport transfer in the world — do it on arrival. China visa planning: extended family members without 10-year visas need to apply for L visas 4-6 weeks in advance.',
    weather: [
      { season: 'Spring', months: 'Mar – May', temp: '55–72°F / 13–22°C', desc: 'Mild, green, cherry blossoms in March. Some rain. Crowds manageable. Good window.', rating: 4 },
      { season: 'Summer', months: 'Jun – Aug', temp: '85–95°F / 30–35°C', desc: 'Very hot and humid. Typhoon risk in July-August. Not recommended for a large family group.', rating: 2 },
      { season: 'Fall', months: 'Sep – Nov', temp: '60–75°F / 16–24°C', desc: 'Best window. Clear skies, comfortable temperatures, lower humidity. Peak season — book early.', rating: 5 },
      { season: 'Winter', months: 'Dec – Feb', temp: '35–48°F / 2–9°C', desc: 'Cold and damp. Shanghai gets grey and chilly in winter. Off-season — avoid.', rating: 2 },
    ],
    kids: [
      'Shanghai Disney Resort — the newest and arguably most beautifully designed Disney park in the world. The Enchanted Storybook Castle is the largest in any Disney park. Full day minimum.',
      'Maglev train from Pudong airport — the world\'s fastest commercial train, reaching 430km/h in 4 minutes. Ride it on arrival. Kids will want to ride it again.',
      'Yu Garden and the Old City — a 16th-century classical garden embedded in a bustling bazaar. Zigzag bridges over koi ponds, pavilions, rockeries.',
      'Shanghai Natural History Museum — exceptional natural history museum with a dinosaur hall, evolution spiral, and exhibits scaled for children.',
      'Tianzifang — a maze of converted shikumen alleyways in the French Concession with art galleries, craft shops, and food stalls. Easy to wander and explore.',
    ],
    family: [
      'DiDi (Chinese Uber) handles all in-city transport — no cars, no navigation, no parking. Essential app; Maggie sets it up for the group.',
      'Maglev from PVG airport (8 min, 430km/h) then metro to hotel — the most thrilling airport transfer in the world.',
      'Both LAX and SEA have nonstop flights with similar flight times — clean symmetric routing.',
      'Mandarin speakers in the group unlock a qualitatively better experience everywhere: real menus, local restaurant recommendations, off-the-tourist-track access.',
      'Visa planning: Maggie/Bill/Jordan already hold 10-year China visas. Extended family members need to apply for L visas 4-6 weeks in advance.',
    ],
    adults: [
      'Ultraviolet by Paul Pairet — 10-seat restaurant where each course is accompanied by projected visuals, scent, and sound. One of the most extraordinary dining experiences in the world. Book months ahead.',
      'The Bund at night — illuminated colonial buildings reflected in the Huangpu River, Pudong skyline behind. Walk it twice: once by day, once by night.',
      'Vue bar at the Hyatt on the Bund — panoramic rooftop bar with the best Bund view in Shanghai. Go at dusk.',
      'Xintiandi — restored shikumen neighborhood turned upscale dining and bars. Where the Chinese Communist Party held its first congress in 1921; now surrounded by restaurants.',
      'Antique markets: Dongtai Road for browsing; Jing\'an antique market for better-quality finds. Mandarin essential for negotiating.',
    ],
    dayTrips: [
      { name: 'Suzhou', desc: '30 min by bullet train. Classical gardens (Humble Administrator\'s Garden, Lingering Garden), canal gondola rides, silk weaving. UNESCO-listed. Full day.' },
      { name: 'Hangzhou + West Lake', desc: '45 min by bullet train. West Lake causeways, pagodas, Dragon Well tea plantations, rowing boats on the lake. One of China\'s most celebrated landscapes. Full day.' },
      { name: 'Zhujiajiao water town', desc: '1 hr by car or bus. Well-preserved Ming/Qing canal town with stone bridges, gondola rides, and local food stalls. Half day; less touristy than most alternatives.' },
    ],
    sketch: [
      { day: 'Sat - Arrive', highlight: 'Land PVG. Maglev to Longyang Road (8 min, 430km/h) + metro to hotel. Check in. Evening Bund walk and Shanghainese dinner near the hotel.' },
      { day: 'Sun - Day 1', highlight: 'The Bund morning + Yu Garden and Old City bazaar (xiaolongbao at Nanxiang) + French Concession afternoon: Wukang Road, Xintiandi.' },
      { day: 'Mon - Day 2', highlight: 'Shanghai Disney Resort: full day. Book in advance.' },
      { day: 'Tue - Day 3', highlight: 'Suzhou day trip: bullet train (30 min). Humble Administrator\'s Garden, canal gondola ride, Pingjiang Road. Lunch in Suzhou.' },
      { day: 'Wed - Day 4', highlight: 'Shanghai Natural History Museum + Tianzifang (lunch and browsing) + Xintiandi afternoon + Vue bar rooftop at dusk.' },
      { day: 'Thu - Day 5', highlight: 'Hangzhou day trip: bullet train (45 min). West Lake causeways, rowing boats, Dragon Well tea plantation. Lunch in Hangzhou.' },
      { day: 'Fri - Day 6', highlight: 'Jing\'an District: Jing\'an Temple + Shanghai Museum of Art + Nanjing Road. Evening: Ultraviolet or high-end Shanghainese dinner (pre-booked).' },
      { day: 'Sat - Day 7', highlight: 'French Concession morning: Fuxing Park, antique markets, final xiaolongbao at Jia Jia Tang Bao. Farewell dinner on the Bund.' },
      { day: 'Sun - Depart', highlight: 'Morning checkout. DiDi or metro to Longyang Road + Maglev to PVG (8 min). Both crews depart direct.' },
    ],
  },

  {
    id: 'chengdu',
    name: 'Chengdu, China',
    regionKey: 'asia',
    regionLabel: 'Asia · China',
    directFlight: true,
    pitch: 'Pandas, bullet trains, Michelin food, and one of China\'s most livable cities — all from a single luxury hotel in the middle of everything.',
    about: 'Chengdu is the capital of Sichuan Province and one of China\'s most beloved cities — famously relaxed for a Chinese megacity, with a culture built around tea houses, street food, and the art of slowing down. It\'s known outside China primarily for its giant pandas, but that undersells it. The food alone is worth the flight: Sichuan cuisine is one of China\'s four great regional culinary traditions, and you\'re eating it at the source.\n\nTwo UNESCO World Heritage Sites — the Leshan Giant Buddha and the Dujiangyan Irrigation System — are reachable by bullet train in under an hour. That means serious day trips with no driving, no car seats, and no hotel changes. For a multi-household family with young kids, this combination of a strong city base and easy day-trip infrastructure is hard to match.',
    gradient: 'linear-gradient(160deg, #7B2D00 0%, #B85420 40%, #E08855 100%)',
    lax: { direct: true, time: '~15h 45m', airlines: 'Sichuan Airlines (3U3838)', notes: '3x/week Tue/Fri/Sun. ~$850 roundtrip. Lands at Chengdu Tianfu (TFU) directly.' },
    sea: { direct: true, time: '13h 25m + 2–2.5h HSR', airlines: 'Hainan Airlines (SEA → CKQ)', notes: 'Direct flight lands at Chongqing (CKQ). Do NOT exit the airport — take HSR from CKQ Terminal 3 directly to Chengdu. Under 2.5h. No separate transfer needed.' },
    timeDiff: '+15h from LA (summer) · +16h (winter)',
    visa: 'Tourist L visa required for most nationalities — apply 4-6 weeks in advance. Maggie/Bill/Jordan already hold 10-year China visas.',
    bestTime: 'Mar – May · Sep – Nov',
    groupNotes: 'Anchor hotel: Grand Hyatt Chengdu. Central location, multiple room categories, hotel airport pickup. Standard King ~$102/night, Grand Suite King ~$144/night, Grand Deluxe Suite King ~$228/night. Alternatives: W Chengdu (~$273/night), Waldorf Astoria Chengdu (~$163/night). All within walking distance of Chunxi Road, IFS Mall, and Taikoo Li. No driving required — everything by DiDi or bullet train. Leshan by bullet train: 50 min. Dujiangyan: 20 min.',
    weather: [
      { season: 'Spring', months: 'Mar – May', temp: '59–73°F / 15–23°C', desc: 'Mild, green, occasional light rain. Cherry blossoms in March. Pandas most active. Best window.', rating: 5 },
      { season: 'Summer', months: 'Jun – Aug', temp: '85–90°F / 30–32°C', desc: 'Hot, humid, heavy afternoon rain. Manageable but not comfortable for a full week with kids.', rating: 2 },
      { season: 'Fall', months: 'Sep – Nov', temp: '60–75°F / 16–24°C', desc: 'Clear skies, comfortable, fewer crowds than spring. Second-best window.', rating: 5 },
      { season: 'Winter', months: 'Dec – Feb', temp: '40–50°F / 4–10°C', desc: 'Cold, foggy, damp. Chengdu rarely gets sun in winter. Off-season — avoid.', rating: 2 },
    ],
    kids: [
      'Giant Panda Breeding Research Base — opens 7:30am; go at opening. Pandas active in the morning. Cubs in the nursery. Red pandas roaming freely. 20 min from hotel. The single best kid experience on this trip.',
      'Dujiangyan Panda Valley — smaller and more intimate than the main base. Volunteer to help feed pandas if booked in advance. Less crowded, more hands-on.',
      'Leshan Giant Buddha — a 233-foot statue carved directly into a cliff face, viewed from a river boat. The scale is genuinely incomprehensible until you\'re in front of it.',
      'Sichuan Opera, Bian Lian (face-changing) — performers swap elaborately painted masks in milliseconds with no visible mechanism. Kids are completely mystified.',
      'People\'s Park Children\'s Paradise — playground and carnival rides inside the park; good for burning energy while adults decompress at the adjacent Singing Crane teahouse.',
    ],
    family: [
      'Grand Hyatt location is purpose-built for a large group — walking distance to Chunxi Road, IFS Mall, and Taikoo Li, with dozens of restaurants at every price point within 5 minutes on foot.',
      'No driving required for the core itinerary. Everything moves by DiDi or bullet train. No car seats needed.',
      'Bullet train logistics are straightforward: Leshan in 50 min, Dujiangyan in 20 min. Everyone boards at the same station, arrives together.',
      'Chinese culture is multigenerationally warm. Grandparents are treated with great respect; children are adored. This destination works for every age in the group.',
      'Mandarin speakers in the group unlock a meaningfully better experience everywhere: real menus, local spots, negotiating at markets.',
    ],
    adults: [
      'Ma Wang Zi (马旺子) — 1 Michelin star, traditional Sichuan cuisine. Reservation required.',
      'Da Dong Roast Duck — 1 Michelin star. Surprisingly one of the best versions of Beijing duck anywhere, including Beijing.',
      'Jiangfu 1776 (将府1776) — upscale Sichuan hotpot. Order the premium broth, the tripe, the wagyu.',
      'Taikoo Li — open-air luxury retail and dining complex built around a historic temple courtyard. Architecturally striking.',
      'Zhongshu Library (钟书阁) — one of China\'s most extraordinary bookstores. Floor-to-ceiling mirrored shelves, cathedral scale.',
    ],
    dayTrips: [
      { name: 'Leshan Giant Buddha', desc: '50 min by bullet train. Take the river boat view (not the cliff stairs). A 233-foot statue carved into a cliff, incomprehensible until you\'re in front of it. Lunch in Leshan. Back by late afternoon.' },
      { name: 'Dujiangyan Panda Valley + Mount Qingcheng', desc: '20 min by bullet train. Combine both in one day: panda sanctuary in the morning (hands-on, less crowded than the main base), then hike through a Taoist sacred mountain with ancient temples in the trees. Full day.' },
    ],
    sketch: [
      { day: 'Sat - Arrive', highlight: 'Land at TFU (LAX crew via Sichuan Air) or transfer from CKQ via HSR (2-2.5h) (SEA crew). Check in Grand Hyatt. Walk to Taikoo Li for dinner.' },
      { day: 'Sun - Day 1', highlight: 'Wide and Narrow Alley in the morning (go early) + People\'s Park tea house in the afternoon. Sichuan hotpot dinner at Jiangfu 1776.' },
      { day: 'Mon - Day 2', highlight: 'Qingyang Palace + Culture Park + afternoon shopping at IFS and Chunxi Road. Dinner: Ma Wang Zi (Michelin, pre-booked).' },
      { day: 'Tue - Day 3', highlight: 'Giant Panda Breeding Research Base: arrive at 7:30am opening. Back by noon. Dim sum lunch at 点都德. Afternoon rest.' },
      { day: 'Wed - Day 4', highlight: 'Leshan Giant Buddha day trip: bullet train, river boat view, local lunch. Back by early evening.' },
      { day: 'Thu - Day 5', highlight: 'Wuhou Temple + Jinli Old Street morning + Chengdu Global Center afternoon + Sichuan Opera (Bian Lian face-changing) evening.' },
      { day: 'Fri - Day 6', highlight: 'Dujiangyan Panda Valley + Mount Qingcheng day trip. Full day out. Dinner back in the city.' },
      { day: 'Sat - Day 7', highlight: 'Morning at leisure. Final Sichuan meal: Da Dong Roast Duck or one last hotpot. Walk through Taikoo Li. Pack.' },
      { day: 'Sun - Depart', highlight: 'Morning checkout. TFU for LAX crew (Sichuan Air). CKQ via HSR from Terminal 3 (2-2.5h) for SEA crew.' },
    ],
  },

  {
    id: 'hongkong',
    name: 'Hong Kong',
    regionKey: 'asia',
    regionLabel: 'Asia · Hong Kong',
    directFlight: true,
    pitch: 'A vertical city like no other — harbor views, dim sum at 6am, and the most efficient transit system in the world crammed into one of the world\'s most dramatic natural settings.',
    about: 'Hong Kong is one of the great urban experiences in the world — a dense, vertical, relentlessly energetic city built on a series of steep islands and a peninsula, with a working harbor at the center and mountains rising directly from the urban grid. The skyline from the Kowloon waterfront at night is among the most photographed views on earth, and it earns it.\n\nFor a large family group, Hong Kong has a uniquely clean logistical profile. No visa required for US citizens. English is widely spoken and officially recognized. The MTR is the best urban transit system in the world. Octopus cards cover every train, bus, tram, and ferry. Day trips to Macau (1 hour by ferry), Shenzhen (40 min by MTR), and Lantau Island are easy. For a group with mixed China experience, Hong Kong is the softest possible landing into the region.',
    gradient: 'linear-gradient(160deg, #6B0A1A 0%, #A82030 40%, #D05050 100%)',
    lax: { direct: true, time: '~13h 30m', airlines: 'Cathay Pacific (LAX → HKG)', notes: 'Daily nonstop from LAX to HKG. LAX is actually slightly shorter than SEA on this route. Both crews land at the same airport on the same excellent carrier.' },
    sea: { direct: true, time: '14h', airlines: 'Cathay Pacific (SEA → HKG)', notes: 'Nonstop to Hong Kong International Airport (HKG). Cathay Pacific is consistently rated among the world\'s best airlines.' },
    timeDiff: '+15h from LA (summer) · +16h (winter)',
    visa: 'Visa-free for US citizens up to 90 days. No application needed. Hong Kong operates under a separate immigration system from mainland China — a China visa does not cover Hong Kong.',
    bestTime: 'Oct – Dec',
    groupNotes: 'Anchor hotel: The Peninsula Hong Kong (Tsim Sha Tsui, Kowloon, $700-1,300/night) — the grand dame of Hong Kong hotels since 1928, fleet of Rolls-Royce transfers, harbor-view rooms. Rosewood Hong Kong (also Kowloon, modern alternative) at similar rates. Kowloon-side is the better base: best harbor views, direct Star Ferry to Central, easy MTR connections. Octopus cards: buy at the airport MTR station on arrival — covers everything. Airport Express from HKG to Kowloon: 22 minutes.',
    weather: [
      { season: 'Spring', months: 'Mar – May', temp: '65–78°F / 18–26°C', desc: 'Warming but humid and hazy. Some rain. Harbor view visibility often compromised. Not ideal.', rating: 3 },
      { season: 'Summer', months: 'Jun – Sep', temp: '85–93°F / 30–34°C', desc: 'Very hot, extremely humid, typhoon season July-September. Typhoons can disrupt plans significantly. Avoid.', rating: 2 },
      { season: 'Fall', months: 'Oct – Dec', temp: '68–78°F / 20–26°C', desc: 'Best window by a wide margin. Clear skies, low humidity, comfortable temperatures, excellent harbor visibility. October and November are peak.', rating: 5 },
      { season: 'Winter', months: 'Jan – Feb', temp: '55–65°F / 13–18°C', desc: 'Cool and dry. Clear skies. Quiet season with lower prices. Good alternative window.', rating: 4 },
    ],
    kids: [
      'Peak Tram and Victoria Peak — a 125-year-old funicular railway up a nearly vertical incline. The view of the harbor and skyline from the Peak is the defining image of Hong Kong.',
      'Star Ferry across Victoria Harbour — a 10-minute ferry ride running since 1888. One of the world\'s great short journeys. Takes the MTR every time.',
      'Macau — 1-hour TurboJet ferry from Hong Kong. The Ruins of St. Paul\'s, Senado Square, and the Venetian Cotai has an actual gondola canal inside — kids find it surreal. Lord Stow\'s egg tarts are among the best in the world.',
      'Shenzhen — 40 min by MTR. Window of the World theme park has 130 miniature replicas of world landmarks. Genuinely fun and slightly absurd in the best way. China visa required — plan accordingly.',
      'Ngong Ping 360 cable car + Giant Buddha (Lantau Island) — 25-minute gondola ride across mountains to a 34-metre Buddha approached by 268 steps.',
    ],
    family: [
      'No visa required for US citizens — the cleanest Asia entry on this list.',
      'English everywhere — signage, menus, transit announcements. No language barrier for any member of the group.',
      'MTR is effortless for a large group — Octopus cards work on every form of transport. Buy at any station on arrival.',
      'Cathay Pacific on both LAX and SEA — no carrier coordination complexity for the two crews.',
      'October-December is ideal: dry, clear, 70-78°F, low humidity. The harbor views are clearest in autumn.',
    ],
    adults: [
      'Lung King Heen (Four Seasons) — three Michelin stars, harbor view, arguably the finest Cantonese restaurant in the world. Book weeks ahead.',
      'Yat Lok roast goose — Michelin-starred, cash only, no reservations. Queue from 11am. The roast goose is extraordinary.',
      'Macau food and history — Macanese cuisine (Portuguese-Chinese fusion) exists nowhere else in the world. African chicken, bacalhau, Lord Stow\'s egg tarts. The UNESCO historic center is compact and walkable.',
      'Shenzhen as a modern China contrast — crossing from colonial Hong Kong into the most aggressively modern city in China in 40 minutes. OCT Loft is an excellent contemporary art and design district. Food is outstanding and cheap.',
      'Ozone bar at the Ritz-Carlton (ICC Tower, 118th floor) — the world\'s highest bar. Cocktails with a view over the entire territory at dusk.',
    ],
    dayTrips: [
      { name: 'Macau', desc: '1 hr by TurboJet ferry from the Macau Ferry Terminal or Kowloon. UNESCO colonial architecture, Ruins of St. Paul\'s, Cotai casino strip, and Macanese food (Portuguese-Chinese fusion). Full day or easy overnight.' },
      { name: 'Lantau Island', desc: 'MTR to Tung Chung + Ngong Ping 360 cable car. Giant Buddha, Tai O fishing village (stilt houses over water), and beaches on the south coast. Full day within the territory.' },
      { name: 'Cheung Chau Island', desc: '35-min ferry from Central Pier. Car-free island with temples, seafood restaurants, and a beach. Kids can rent bikes. Easy half-day contrast to the city.' },
      { name: 'Dragon\'s Back hike', desc: 'Bus from Shau Kei Wan MTR to the trailhead. 2-3 hour ridge walk with South China Sea views, then descend to Shek O beach for lunch. Best urban hike in Hong Kong.' },
      { name: 'Shenzhen (China visa required)', desc: '40 min by MTR East Rail to Lo Wu border. Huaqiangbei electronics market, OCT Loft creative district, excellent food. Full day. Mainland China: Maggie/Bill/Jordan have 10-year visas; extended family needs to check visa status.' },
    ],
    sketch: [
      { day: 'Sat - Arrive', highlight: 'Land HKG. Airport Express to Kowloon (22 min). Check in. Star Ferry to Central and back. Dinner at a Tsim Sha Tsui Cantonese restaurant.' },
      { day: 'Sun - Day 1', highlight: 'Dim sum breakfast (yum cha) + Peak Tram up to Victoria Peak + tram ride along Hong Kong Island north shore + Symphony of Lights harbor show (8pm).' },
      { day: 'Mon - Day 2', highlight: 'Macau day trip: TurboJet ferry (1 hr). Ruins of St. Paul\'s, Senado Square, Macanese lunch, Cotai optional. Back by evening.' },
      { day: 'Tue - Day 3', highlight: 'Lantau Island: MTR to Tung Chung + Ngong Ping 360 cable car + Giant Buddha + Tai O fishing village. Back by late afternoon.' },
      { day: 'Wed - Day 4', highlight: 'Hong Kong Island: Central Market + PMQ + Hollywood Road antiques + Man Mo Temple + Wan Chai for dinner (Yat Lok roast goose).' },
      { day: 'Thu - Day 5', highlight: 'Dragon\'s Back hike (morning, bus from Shau Kei Wan) + Shek O beach lunch + afternoon at leisure or Ocean Park for the kids.' },
      { day: 'Fri - Day 6', highlight: 'Shenzhen day trip: MTR East Rail to Lo Wu (40 min). Huaqiangbei electronics market, OCT Loft, lunch in Shenzhen. Back by evening. (China visa required)' },
      { day: 'Sat - Day 7', highlight: 'Temple Street Night Market + Kowloon waterfront walk + farewell Cantonese dinner at Lung King Heen (pre-booked) or a classic dai pai dong.' },
      { day: 'Sun - Depart', highlight: 'Morning checkout. Airport Express from Kowloon station (22 min to HKG). Both crews depart direct on Cathay Pacific.' },
    ],
  },

  {
    id: 'singapore',
    name: 'Singapore',
    regionKey: 'asia',
    regionLabel: 'Asia · Singapore',
    directFlight: true,
    pitch: 'The cleanest, most efficient city-state in the world — where a hawker centre meal costs $4 and the Gardens by the Bay look like a science fiction film set come to life.',
    about: 'Singapore is a city-state of 5.9 million people on an island roughly the size of Chicago, engineered with extraordinary intentionality. The streets are immaculate, the transit system is world-class, the food is outstanding at every price point, and the tropical gardens and architecture are unlike anything else on this list. It is the easiest city in Asia to visit — English is the primary working language, signage is universal, and the infrastructure is designed to be navigated effortlessly.\n\nThe signature experiences — Gardens by the Bay, Marina Bay Sands, Sentosa Island, the hawker centres — all deliver in person. Gardens by the Bay\'s Supertrees are 16-story vertical gardens that look impossible until you\'re standing under them. The hawker centres serve some of the best food in the world at $3-8 per dish. The flight is the longest on this list, but Singapore Airlines makes it better than almost any other airline in the world.',
    gradient: 'linear-gradient(160deg, #0A2E1A 0%, #1A6045 40%, #3A9870 100%)',
    lax: { direct: true, time: '~17h', airlines: 'Singapore Airlines (LAX → SIN)', notes: 'Daily nonstop from LAX to Changi (SIN). Singapore Airlines operates both routes. Longest flight on this list — business class or premium economy strongly recommended if budget allows.' },
    sea: { direct: true, time: '16h 30m', airlines: 'Singapore Airlines (SEA → SIN)', notes: 'Nonstop to Singapore Changi Airport (SIN). Singapore Airlines is consistently rated the world\'s best airline — the flight experience itself is a highlight.' },
    timeDiff: '+15h from LA (summer) · +16h (winter)',
    visa: 'Visa-free for US citizens up to 90 days. No application needed.',
    bestTime: 'Nov – Jan',
    groupNotes: 'Anchor hotel: Marina Bay Sands ($700-1,400/night) — 2,561 rooms, infinity pool on the 57th floor, adjacent to Gardens by the Bay. Capella Singapore (Sentosa Island, $800-1,400/night) is the quiet luxury alternative with a resort feel. EZ-Link transit cards: buy at any MRT station on arrival — covers all MRT, buses, and some attractions. Grab (Singapore\'s Uber equivalent) covers everything the MRT doesn\'t. No car rental needed. Singapore Airlines on both routes — no carrier coordination complexity for the two crews.',
    weather: [
      { season: 'Nov – Jan', months: 'Nov – Jan', temp: '77–84°F / 25–29°C', desc: 'Best window. Lower humidity, occasional afternoon showers but generally manageable. Comfortable for outdoor activities.', rating: 5 },
      { season: 'Feb – Mar', months: 'Feb – Mar', temp: '79–86°F / 26–30°C', desc: 'Hot and humid. Some rain. Still pleasant for short periods outdoors. Good value season.', rating: 4 },
      { season: 'Jun – Sep', months: 'Jun – Sep', temp: '82–88°F / 28–31°C', desc: 'Hot, humid, occasional haze from Indonesian fires in August-September. Manageable but not the best version.', rating: 3 },
      { season: 'Oct', months: 'Oct', temp: '79–86°F / 26–30°C', desc: 'Wettest month of the year. Heavy afternoon downpours. Avoid if possible.', rating: 2 },
    ],
    kids: [
      'Gardens by the Bay Supertrees — 16-story vertical gardens that light up at night in a sound-and-light show (Garden Rhapsody, 7:45pm and 8:45pm nightly). The Cloud Forest has a 35-metre indoor waterfall.',
      'Universal Studios Singapore (Sentosa) — Southeast Asia\'s only Universal Studios. Jurassic World, Transformers, Minion Park. Good for a full day.',
      'Singapore Zoo + Night Safari — the zoo is excellent internationally. The Night Safari adjacent is a unique experience: a tram through a nocturnal wildlife park after dark. Animals are active; the atmosphere is unlike any daytime zoo.',
      'S.E.A. Aquarium (Sentosa) — one of the largest aquariums in the world. Open ocean habitat with manta rays and over 100,000 marine animals.',
      'Marina Bay Sands infinity pool — hotel guests only, 57th floor, appears to extend over the Singapore skyline. The defining visual memory of the trip.',
    ],
    family: [
      'English everywhere — the only Asia destination on this list with zero language barrier for non-Mandarin speakers. Menus, transit, and conversations fully accessible.',
      'No visa required for US citizens — alongside Hong Kong, the easiest Asia entry on this list.',
      'MRT is excellent — clean, fast, air-conditioned, and well-mapped in English. EZ-Link cards cover all transit.',
      'Hawker centre dinners are the ideal large-group meal: no reservation, everyone picks their own dish from different stalls, total cost for the group is negligible.',
      'Singapore Airlines on both routes — the flight experience is genuinely exceptional, which matters when it\'s 16-17 hours.',
    ],
    adults: [
      'Odette at the National Gallery — 3 Michelin stars, one of Asia\'s best restaurants. Book well in advance.',
      'Burnt Ends — wood-fire barbecue with a cult following. Small space, open kitchen, counter seating. Book weeks ahead or queue at opening.',
      '1-Altitude rooftop bar (282m) — the highest al fresco bar in the world. Views across the city and harbor at dusk.',
      'Ann Siang Hill and Club Street — restored colonial shophouses converted into excellent bars and restaurants. The Peranakan neighborhood feel is distinct and worth an evening.',
      'Baba House — a beautifully restored Peranakan heritage house in Blair Road. Guided tours only, book in advance. One of the best windows into Singapore\'s layered cultural history.',
    ],
    dayTrips: [
      { name: 'Sentosa Island', desc: 'Connected by bridge, cable car, or monorail. Universal Studios, S.E.A. Aquarium, Siloso and Palawan beaches, Resorts World. Can easily fill 1-2 full days. Within Singapore territory.' },
      { name: 'Johor Bahru, Malaysia', desc: '1 hr by bus across the Causeway. Shopping, food, and a completely different atmosphere at a fraction of Singapore prices. Easy half-day. Malaysian customs required: bring passports.' },
      { name: 'Bintan Island, Indonesia', desc: '45-min ferry from Tanah Merah Ferry Terminal. Beach resorts, mangroves, and a slower pace than Singapore. Best as an overnight extension.' },
      { name: 'Pulau Ubin', desc: '10-min bumboat from Changi Village. Rustic island with kampung (village) atmosphere, cycling trails, and mangrove wetlands. Almost no development. Total contrast to the city. Half day.' },
    ],
    sketch: [
      { day: 'Sat - Arrive', highlight: 'Land SIN at Changi (world\'s best airport: allow time to explore Jewel). MRT to hotel. Check in. Marina Bay waterfront evening walk. Hawker centre dinner at Lau Pa Sat.' },
      { day: 'Sun - Day 1', highlight: 'Gardens by the Bay: Flower Dome + Cloud Forest conservatories + Supertree Grove sky walkway + Garden Rhapsody light show (7:45pm).' },
      { day: 'Mon - Day 2', highlight: 'Sentosa Island full day: Universal Studios or S.E.A. Aquarium + beach afternoon at Siloso or Palawan. Cable car back to mainland at sunset.' },
      { day: 'Tue - Day 3', highlight: 'Singapore Zoo (morning) + Night Safari (evening). Afternoon rest at hotel between visits.' },
      { day: 'Wed - Day 4', highlight: 'Cultural Singapore: Chinatown (Buddha Tooth Relic Temple, Maxwell Food Centre chicken rice) + Little India + Arab Street + Haji Lane. Hawker dinner at Newton Food Centre.' },
      { day: 'Thu - Day 5', highlight: 'Colonial Singapore: Raffles Hotel + National Museum + Fort Canning Park + Botanic Gardens (National Orchid Garden). Ann Siang Hill for dinner.' },
      { day: 'Fri - Day 6', highlight: 'Pulau Ubin day trip (bumboat from Changi Village, half day cycling) + back for afternoon at leisure + farewell dinner at Odette or Burnt Ends (pre-booked).' },
      { day: 'Sat - Day 7', highlight: 'Jewel Changi Airport (HSBC Rain Vortex: world\'s tallest indoor waterfall, 40m, inside the terminal) + final hawker lunch + pack.' },
      { day: 'Sun - Depart', highlight: 'Morning checkout. MRT to Changi Airport (direct). Both crews depart direct on Singapore Airlines.' },
    ],
  },

];
